<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<h6 style="text-align:justify;font-family:times new roman;font-size:15px;">In the developed world, most blood donors are unpaid volunteers (voluntary non remunerated repeat donations, VNRD) who give blood for a community supply. In poorer countries, established supplies are limited and donors usually give blood when family or friends need a transfusion. Many donors donate as an act of charity, but some are paid and in some cases there are incentives other than money such as paid time off from work. Donors can also have blood drawn for their own future use. 
                Donating is relatively safe, but some donors have bruising where the needle is inserted or may feel faint. </p>

<br>
<p>The World Health Organization set a goal in 1997 for all blood donations to come from unpaid volunteer donors, but as of 2006, only 49 of 124 countries surveyed had established this as a standard.<sup id="cite_ref-WBDD_2006_11-2" class="reference"><a href="#cite_note-WBDD_2006-11"><span>[</span>12<span>]</span></a></sup> Some countries, such as <a href="/wiki/Tanzania" title="Tanzania">Tanzania</a>, have made great strides in moving towards this standard, with 20 percent of donors in 2005 being unpaid volunteers and 80 percent in 2007, but 68 of 124 countries surveyed by WHO had made little or no progress.<sup id="cite_ref-PEPFAR_Progress_4-1" class="reference"><a href="#cite_note-PEPFAR_Progress-4"><span>[</span>5<span>]</span></a></sup> Some <a href="/wiki/Plasmapheresis" title="Plasmapheresis">plasmapheresis</a> donors in the <a href="/wiki/United_States" title="United States">United States</a> are still paid for donations.<sup id="cite_ref-85" class="reference"><a href="#cite_note-85"><span>[</span>86<span>]</span></a></sup> A few countries rely on paid donors to maintain an adequate supply.<sup id="cite_ref-86" class="reference"><a href="#cite_note-86"><span>[</span>87<span>]</span></a></sup> In some countries, for example <a href="/wiki/Brazil" title="Brazil">Brazil</a>, <a href="/wiki/Argentina" title="Argentina">Argentina</a>, <a href="/wiki/Australia" title="Australia">Australia</a> and <a href="/wiki/Bulgaria" title="Bulgaria">Bulgaria</a>, it is illegal to receive any compensation, monetary or otherwise, for the donation of blood or other human tissues.<sup id="cite_ref-87" class="reference"><a href="#cite_note-87"><span>[</span>88<span>]</span></a></sup><sup id="cite_ref-88" class="reference"><a href="#cite_note-88"><span>[</span>89<span>]</span></a></sup></p>
</h6>
<br>
<h4>About Us: </h4><h6 style="text-align:justify;font-family:times new roman;font-size:15px;"><b>
<p><strong>"Blood Donor"</strong> is a non-profitable organization which is striving to build the community of blood donors who can help the people in need of blood. The people registered are volunteered to donate their blood for the right cause. </p>
</h6></b>